[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { path = "src/arch/x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = { path = "src/arch/aarch64" }