[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [target.x86_64-unknown-kernel.dependencies]
# x86_64 = "0.14.3"
# uefi = "0.11.0"

[build-dependencies]
uefi-run = "0.3.3"