dev cargo-params="" qemu-params="-s -d cpu_reset -serial stdio -no-reboot -no-shutdown -enable-kvm" qemu="qemu-system-x86_64":
    #!/bin/sh -e
    if [ "$PWD" == "*phobos" ]; then
        cd kernel
    fi
    cargo build {{ cargo-params }}
    kernel_path=$(cargo build {{ cargo-params }} --message-format=json 2> /dev/null | jq .executable\? | grep -v "null" | sed -e 's/^"//' -e 's/"$//')
    pushd src/arch/amd64/boot > /dev/null
    cargo build {{ cargo-params }}
    efi_path=$(cargo build {{ cargo-params }} --message-format=json 2> /dev/null | jq .executable\? | grep -v "null" | sed -e 's/^"//' -e 's/"$//')
    popd > /dev/null
    if [ -z "$OVMF_PATH" ]; then
      OVMF_PATH="/usr/share/edk2/ovmf/OVMF_CODE.fd"
    fi
    uefi-run --files $efi_path $kernel_path --bios $OVMF_PATH --qemu {{ qemu }} -- {{ qemu-params }}

fix:
    cargo fix --allow-dirty --allow-staged --bins

fmt:
    rustfmt ./**.rs
